---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::primalbedtools=1.0.0
  - conda-forge::biopython=1.86
  - conda-forge::jinja2=3.1.6
  - conda-forge::numpy=2.3.5
  - conda-forge::pandas=2.3.3
  - conda-forge::plotly=6.5.0
